apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: image-verification-success
  namespace: default
spec:
  # More about filtering: https://github.com/knative/eventing/blob/master/docs/broker/filtering.md
  filter:
    sourceAndType:
      source: urn:recog.dev:recog
  subscriber:
  # https://knative.dev/docs/reference/eventing/#SubscriberSpec use uri instead of the service for Aspnet core.
    uri: http://webapp.default.svc.cluster.local/image/event

---

apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: image-verification-failure
  namespace: default
spec:
  # More about filtering: https://github.com/knative/eventing/blob/master/docs/broker/filtering.md
  filter:
    sourceAndType:
      source: urn:recog.dev:recog # ToDo
  subscriber:
  # https://knative.dev/docs/reference/eventing/#SubscriberSpec use uri instead of the service for Aspnet core.
  # Addressing a kn service $$$
    uri: http://webapp.default.svc.cluster.local/image/event