apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: webapp
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "10"
        autoscaling.knative.dev/maxScale: "4"
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
      - image: rinormaloku/lovely-faces-webapp
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: BROKER_URL
          value: http://default-broker.default.svc.cluster.local/ 