kubectl delete -f ./app/recognition-service.yaml
kubectl delete -f ./app/webapp-service.yaml
kubectl delete -f ./app/twitter-service.yaml
kubectl delete -f ./app/image-uploaded-trigger.yaml
kubectl delete -f ./app/image-verification-triggers-update.yaml
docker-compose -f ./app/docker-compose.yaml build
docker-compose -f ./app/docker-compose.yaml push
kubectl apply -f ./app/webapp-service.yaml
kubectl apply -f ./app/recognition-service.yaml
kubectl apply -f ./app/twitter-service.yaml
kubectl apply -f ./app/image-uploaded-trigger.yaml
kubectl apply -f ./app/image-verification-triggers-update.yaml