apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: helloworld-go
  namespace: default
spec:
  template:
    metadata:
      name: helloworld-go-2
    spec:
      containers:
      - image: docker.io/rinormaloku/helloworld-go
        # name: "cool-name"
        env:
        - name: TARGET
          value: "Go Sample v2"
  traffic:
  - tag: current
    revisionName: helloworld-go-1
    percent: 100